import { ChevronRightIcon } from "@heroicons/react/24/solid"
import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { FormEvent, useState } from "react"

const Home: NextPage = () => {
	const [steamId, setSteamId] = useState<string>("")
	const router = useRouter()

	const handleSteamId = (e: FormEvent<HTMLFormElement>) => {
		e.preventDefault()

		void router.push(`/user/${steamId}`)
	}

	return (
		<div className="flex h-screen w-screen items-center justify-center">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-transparent">
				<div className="space-y-2">
					<h2>Enter your SteamID</h2>
					<div className="flex rounded shadow-lg">
						<form onSubmit={(e) => handleSteamId(e)} className="flex">
							<input
								value={steamId}
								onChange={(e) => setSteamId(e.target.value)}
								className="rounded-l p-4 text-4xl outline-none duration-200 focus:ring-4 focus:ring-blue-500/50 dark:bg-gray-900"
								type="text"
							/>
							<button className="h-full rounded-r bg-blue-500 px-6 outline-none duration-200 hover:bg-blue-600 focus:ring-4 focus:ring-blue-500/50 active:bg-blue-700">
								<ChevronRightIcon className="h-8 w-8 text-white" />
							</button>
						</form>
					</div>
				</div>
			</main>
		</div>
	)
}

export default Home
